export const PHRASES = [
  "You're Beautiful",
  "You're Amazing",
  "You're Kind",
  "You're Loved",
  "You're Perfect",
  "You're Wonderful",
  "You're Stunning",
  "You're Brilliant",
  "You're Precious",
  "You're Special",
  "Kimberly",
  "♥",
  "I love you",
  "So proud of you",
  "You shine",
  "You matter",
  "You're enough",
  "You're incredible",
  "You're one of a kind",
  "You make me happy",
  "Thank you for being you",
  "You're the best",
  "You're gorgeous",
  "You're strong",
  "You're brave",
  "You're sweet",
  "You're funny",
  "You're caring",
  "You're talented",
  "You're irreplaceable",
  "Forever yours",
  "♥",
  "Kimberly",
] as const;

export type Phrase = (typeof PHRASES)[number];
